### ISSUE TITLE
ICD-O vocabulary issues

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#240] opened 2020-01-07 22:16 UTC
Issue #1 - Topography   w/o any conditions linked
Issue #2 - ICDO Topogrpahy linked via 'Has Histology   ICDO' to another Topography
Issue #3 - ICDO   Topography not mapped to SNOMED (89 out of 400)
Issue #4 - Topography   concepts without parent concept (315 out of 400)
Queries are in the below spreadsheet.
[ICD-O Issues 2019-12-22.xlsx](https://github.com/OHDSI/OncologyWG/files/4032713/ICD-O.Issues.2019-12-22.xlsx)

**Comment by sratwani** [comment] 2020-01-07 22:28
@ekorchmar has completed the documentation for mapping of ICDO to SNOMED for @cgreich and @rimusia review.

**Comment by sratwani** [comment] 2020-01-08 18:48
@ekorchmar Is it okay to mark this as closed?

**Comment by ekorchmar** [comment] 2020-01-08 19:00
We had a short call with @cgreich today and discussed all remaining issues. Yes, it should be closed.

**Comment by sratwani** [comment] 2020-01-08 19:06
@ekorchmar so the changes are released?

**Comment by sratwani** [comment] 2020-01-16 00:06
Documentation is complete. Changes to vocabulary are still pending.

**Comment by sratwani** [comment] 2020-01-28 00:29
Per call on 1/6/2020, ICDO vocabulary issues have been documented. We standardize ICDO to SNOMED. Overall quality will be much better after SNOMED 3.2 release which is scheduled for April after which the plan is to release the fixes to the ICDO vocabulary issues.

**Comment by ekorchmar** [comment] 2020-02-14 13:53
In our recent correspondence with SNOMED team it was confirmed that ICDO3.2 is expected to be a part of July 2020 release, which unfortunately means that it will be ready for inclusion in OMOP CDM only around October.

**Comment by rimusia** [comment] 2020-02-17 18:57
Issues ##1, 2, and 4 are not related to SNOMED mappings and need to be fixed now. Please let the team know when to expect these fixes.

We detected one more issue #5 that looks quite serious: duplicate concepts, one of each should be deprecated. There are 495 such duplicates:
select count(*) from
(
select count(*) as total
from concept
where vocabulary_id = 'ICDO3'
group by concept_name
having count(*) > 1
) a

An example below includes a reference to SEER which states that 9754/3-C02.9 is deprecated and 9751/3-C02.9 should be used instead:

1.
36554961 | 9754/3-C02.9 | Langerhans cell histiocytosis, disseminated of tongue, NOS | ICDO Condition | Standard | Valid | Condition | ICDO3

https://seer.cancer.gov/seertools/hemelymph/51f6cf5ae3e27c3994bd54b6/

2.
36567447 | 9751/3-C02.9 | Langerhans cell histiocytosis, disseminated of tongue, NOS | ICDO Condition | Standard | Valid | Condition | ICDO3

**Comment by ekorchmar** [comment] 2020-03-07 11:17
I described the ongoning process of ICDO3 fixes on the [wiki article](https://github.com/OHDSI/OncologyWG/wiki/ICD-O#problems-of-current-icd-o-vocabulary-implementation-in-omop-cdm):

Reported issues are caused by problems described in the article.
1. Is actually related to classification level of topography that is never encountered in user data. It's problem number 4 in Wiki article.
2. These relations were built by mistake long time ago. They are invalid.
3. Being adressed by fixing problems 2 and 4 of wiki article
4. Again, problem number 4

**Comment by mgurley** [comment] 2022-11-10 13:12
Closing and placing in the deep backlog to focus the repository.

**Closed by mgurley** 2022-11-10 13:12 UTC
Labels: CDM/Vocabulary Subgroup, ICDO3, Deep Backlog
